-- Sequence for INVALID_TOKEN primary key (replaces UUID generation)
CREATE SEQUENCE IF NOT EXISTS INVALID_TOKEN_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Migrate existing UUID ID column to a BIGINT backed by the sequence
ALTER TABLE INVALID_TOKEN
    ALTER COLUMN ID DROP DEFAULT;

ALTER TABLE INVALID_TOKEN
    ALTER COLUMN ID TYPE BIGINT USING nextval('INVALID_TOKEN_SEQ');

ALTER TABLE INVALID_TOKEN
    ALTER COLUMN ID SET DEFAULT nextval('INVALID_TOKEN_SEQ');

ALTER SEQUENCE INVALID_TOKEN_SEQ OWNED BY INVALID_TOKEN.ID;

-- Add expiry column so rows can be pruned once the token has naturally expired
ALTER TABLE INVALID_TOKEN
    ADD COLUMN IF NOT EXISTS EXPIRES_AT TIMESTAMP(6) NOT NULL DEFAULT NOW();

-- Index for efficient cleanup queries
CREATE INDEX IF NOT EXISTS idx_invalid_token_expires_at ON INVALID_TOKEN(EXPIRES_AT);

-- Remove the DEFAULT NOW() fallback — future inserts must supply an explicit value
ALTER TABLE INVALID_TOKEN
    ALTER COLUMN EXPIRES_AT DROP DEFAULT;
