version: "3.9"

services:

  eurekaserver:
    image: eurekaserver:latest
    build:
      context: ./eurekaserver
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SPRING_APPLICATION_NAME=eurekaserver
      - EUREKA_INSTANCE_HOSTNAME=localhost
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - SERVER_PORT=8761
    networks:
      - opensourceworkforcemanagement

  apigateway:
    image: apigateway:latest
    build:
      context: ./apigateway
      dockerfile: Dockerfile
    ports:
      - "1110:1110"
    environment:
      - SPRING_APPLICATION_NAME=apigateway
      - EUREKA_SERVICE_URL=http://eurekaserver:8761/eureka/
    depends_on:
      eurekaserver:
        condition: service_started
    networks:
      - opensourceworkforcemanagement

  authservice:
    image: authservice:latest
    build:
      context: ./authservice
      dockerfile: Dockerfile
    ports:
      - "1112:1112"
    environment:
      - server.port=1112
      - SPRING_APPLICATION_NAME=authservice
      - EUREKA_SERVICE_URL=http://eurekaserver:8761/eureka/
    depends_on:
      eurekaserver:
        condition: service_started
    networks:
      - opensourceworkforcemanagement

  userservice:
    image: userservice:latest
    build:
      context: ./userservice
      dockerfile: Dockerfile
    ports:
      - "1113:1113"
    environment:
      - server.port=1113
      - SPRING_APPLICATION_NAME=userservice
      - EUREKA_SERVICE_URL=http://eurekaserver:8761/eureka/
      - SECURITY_DB_IP=localhost
      - SECURITY_DB_PORT=5432
      - spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/opensourceworkforcemanagement
      - spring.datasource.username=${DATABASE_USERNAME}
      - spring.datasource.password=${DATABASE_PASSWORD}
    depends_on:
      eurekaserver:
        condition: service_started
    networks:
      - opensourceworkforcemanagement

  timesheetservice:
    image: timesheetservice:latest
    build:
      context: ./timesheetservice
      dockerfile: Dockerfile
    ports:
      - "1114:1114"
    environment:
      - server.port=1114
      - SPRING_APPLICATION_NAME=timesheetservice
      - EUREKA_SERVICE_URL=http://eurekaserver:8761/eureka/
      - SECURITY_DB_IP=localhost
      - SECURITY_DB_PORT=5432
      - spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/opensourceworkforcemanagement
      - spring.datasource.username=${DATABASE_USERNAME}
      - spring.datasource.password=${DATABASE_PASSWORD}
    depends_on:
      eurekaserver:
        condition: service_started
    networks:
      - opensourceworkforcemanagement


networks:
  opensourceworkforcemanagement:
    driver: bridge