server:
  port: 1110

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      httpclient:
        connect-timeout: 60000
        response-timeout: 60s

# Internal service base URL used by UserServiceWebClient (BFF auth controller)
services:
  userservice-url: lb://userservice

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
      
# Logging Configuration
logging:
  level:
    org.springframework.security.web.access.ExceptionTranslationFilter: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.web.authentication: DEBUG
    org.springframework.security.web.access.intercept.FilterSecurityInterceptor: DEBUG
    org.springframework.security.access.intercept.AbstractSecurityInterceptor: DEBUG
    root: INFO
  
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  
  file:
    name: ${LOG_FILE_PATH:logs/apigateway.log}
    max-size: ${LOG_MAX_SIZE:50MB}
    max-history: ${LOG_MAX_HISTORY:30}
    total-size-cap: ${LOG_TOTAL_SIZE:1GB}
  
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE_PATH:logs/apigateway}-%d{yyyy-MM-dd}-%i.log
      max-file-size: ${LOG_MAX_SIZE:50MB}
      max-history: ${LOG_MAX_HISTORY:30}
      total-size-cap: ${LOG_TOTAL_SIZE:1GB}