package org.oswfm.commons.model.common;

import lombok.Data;

import java.util.HashMap;
import java.util.Map;

/**
 * Generic REST message envelope shared across services.
 *
 * Example:
 * {
 *   "id": "evt-001",
 *   "type": "ALERT",
 *   "sequence": 1,
 *   "timestamp": 1741651200000,
 *   "source": "notificationservice",
 *   "payload": {
 *     "title": "Hello",
 *     "body": "Test notification",
 *     "data": {}
 *   }
 * }
 */
@Data
public class RestMessageRequest {

    /** Unique event identifier. Auto-generated by receiver if omitted. */
    private String id;

    /** Message type / Kafka topic routing key (e.g. "ALERT", "INCIDENT"). */
    private String type;

    /** Monotonically increasing counter for ordering and replay-from-sequence. */
    private long sequence;

    /** Unix epoch milliseconds. Auto-set by receiver if omitted. */
    private long timestamp;

    /** Originating service or component name. */
    private String source;

    private Payload payload;

    @Data
    public static class Payload {

        /**
         * Delivery priority hint forwarded to FCM.
         * Accepted values: "HIGH", "NORMAL". Defaults to "HIGH" if omitted.
         */
        private String priority = "HIGH";

        /**
         * Time-to-live in milliseconds. Clients should discard the event if
         * (timestamp + ttl) has already passed. 0 means no expiry.
         */
        private long ttl;

        /** Notification headline — maps to FCM notification.title and browser Notification.title. */
        private String title;

        /**
         * Human-readable detail text shown beneath the title in the notification tray.
         * Maps to FCM notification.body and browser Notification.body.
         */
        private String body;

        /** Deep-link URL or named action the client should perform on tap/click. */
        private String clickAction;

        /** Optional image URL displayed in the notification (supported by FCM and modern browsers). */
        private String imageUrl;

        /**
         * Arbitrary key-value pairs forwarded to FCM data payload and WebSocket clients.
         * Values must be strings (FCM requirement). Use this for structured context such as
         * incident IDs, coordinates, or camera references.
         */
        private Map<String, String> data = new HashMap<>();
    }
}
